In [122]:
import numpy as np
import pandas as pd

In [124]:
match=pd.read_csv('matches.csv')
delivery=pd.read_csv('deliveries.csv')

In [125]:
match.tail()

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
1090,1426307,2024,Hyderabad,2024-05-19,League,Abhishek Sharma,"Rajiv Gandhi International Stadium, Uppal, Hyd...",Punjab Kings,Sunrisers Hyderabad,Punjab Kings,bat,Sunrisers Hyderabad,wickets,4.0,215.0,20.0,N,NaN,Nitin Menon,VK Sharma
1091,1426309,2024,Ahmedabad,2024-05-21,Qualifier 1,MA Starc,"Narendra Modi Stadium, Ahmedabad",Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,bat,Kolkata Knight Riders,wickets,8.0,160.0,20.0,N,NaN,AK Chaudhary,R Pandit
1092,1426310,2024,Ahmedabad,2024-05-22,Eliminator,R Ashwin,"Narendra Modi Stadium, Ahmedabad",Royal Challengers Bengaluru,Rajasthan Royals,Rajasthan Royals,field,Rajasthan Royals,wickets,4.0,173.0,20.0,N,NaN,KN Ananthapadmanabhan,MV Saidharshan Kumar
1093,1426311,2024,Chennai,2024-05-24,Qualifier 2,Shahbaz Ahmed,"MA Chidambaram Stadium, Chepauk, Chennai",Sunrisers Hyderabad,Rajasthan Royals,Rajasthan Royals,field,Sunrisers Hyderabad,runs,36.0,176.0,20.0,N,NaN,Nitin Menon,VK Sharma
1094,1426312,2024,Chennai,2024-05-26,Final,MA Starc,"MA Chidambaram Stadium, Chepauk, Chennai",Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,bat,Kolkata Knight Riders,wickets,8.0,114.0,20.0,N,NaN,J Madanagopal,Nitin Menon

In [128]:
delivery.tail()

,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder
260915,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,9,5,SS Iyer,AK Markram,VR Iyer,1,0,1,NaN,0,NaN,NaN,NaN
260916,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,9,6,VR Iyer,AK Markram,SS Iyer,1,0,1,NaN,0,NaN,NaN,NaN
260917,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,1,VR Iyer,Shahbaz Ahmed,SS Iyer,1,0,1,NaN,0,NaN,NaN,NaN
260918,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,2,SS Iyer,Shahbaz Ahmed,VR Iyer,1,0,1,NaN,0,NaN,NaN,NaN
260919,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,3,VR Iyer,Shahbaz Ahmed,SS Iyer,1,0,1,NaN,0,NaN,NaN,NaN

Now for Regression Model we need data like batting team(in 2nd innings) ,bolwing team,runs to be chased in required number of balls,match id

In [131]:
match['team1'].unique()

array(['Royal Challengers Bangalore', 'Kings XI Punjab',
       'Delhi Daredevils', 'Mumbai Indians', 'Kolkata Knight Riders',
       'Rajasthan Royals', 'Deccan Chargers', 'Chennai Super Kings',
       'Kochi Tuskers Kerala', 'Pune Warriors', 'Sunrisers Hyderabad',
       'Gujarat Lions', 'Rising Pune Supergiants',
       'Rising Pune Supergiant', 'Delhi Capitals', 'Punjab Kings',
       'Lucknow Super Giants', 'Gujarat Titans',
       'Royal Challengers Bengaluru'], dtype=object)

In [133]:
teams=[
    'Royal Challengers Bengaluru',
    'Mumbai Indians',
    'Kolkata Knight Riders',
    'Rajasthan Royals',
    'Chennai Super Kings',
    'Sunrisers Hyderabad',
    'Lucknow Super Giants',
    'Gujarat Titans',
    'Delhi Capitals',
    'Punjab Kings'
]

In [135]:
match['team1']=match['team1'].str.replace('Royal Challengers Bangalore','Royal Challengers Bengaluru')
match['team2']=match['team2'].str.replace('Royal Challengers Bangalore','Royal Challengers Bengaluru')

match['team1']=match['team1'].str.replace('Kings XI Punjab','Punjab Kings')
match['team2']=match['team2'].str.replace('Kings XI Punjab','Punjab Kings')

match['team1']=match['team1'].str.replace('Deccan Chargers','Sunrisers Hyderabad')
match['team2']=match['team2'].str.replace('Deccan Chargers','Sunrisers Hyderabad')

match['team1']=match['team1'].str.replace('Gujarat Lions','Gujarat Titans')
match['team2']=match['team2'].str.replace('Gujarat Lions','Gujarat Titans')

match['team1']=match['team1'].str.replace('Delhi Daredevils','Delhi Capitals')
match['team2']=match['team2'].str.replace('Delhi Daredevils','Delhi Capitals')

In [137]:
match=match[match['team1'].isin(teams)]
match=match[match['team2'].isin(teams)]

In [139]:
match['team1'].unique()

array(['Royal Challengers Bengaluru', 'Punjab Kings', 'Delhi Capitals',
       'Mumbai Indians', 'Kolkata Knight Riders', 'Rajasthan Royals',
       'Sunrisers Hyderabad', 'Chennai Super Kings', 'Gujarat Titans',
       'Lucknow Super Giants'], dtype=object)

In [141]:
delivery=delivery[delivery['inning']==1]

In [143]:
match['winner'] = match.apply(lambda row: row['team1'] if "runs" in row['result'] 
                                    else (row['team2'] if "wickets" in row['result'] 
                                          else "Draw/Tie"), axis=1)

In [145]:
match = match[['id', 'city', 'winner', 'target_runs']]

In [147]:
match=match.merge(delivery,left_on='id',right_on='match_id')

In [149]:
match

,id,city,winner,target_runs,match_id,inning,batting_team,bowling_team,over,ball,...,bowler,non_striker,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder
0,335982,Bangalore,Royal Challengers Bengaluru,223.0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,...,P Kumar,BB McCullum,0,1,1,legbyes,0,NaN,NaN,NaN
1,335982,Bangalore,Royal Challengers Bengaluru,223.0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,...,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
2,335982,Bangalore,Royal Challengers Bengaluru,223.0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,...,P Kumar,SC Ganguly,0,1,1,wides,0,NaN,NaN,NaN
3,335982,Bangalore,Royal Challengers Bengaluru,223.0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,...,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
4,335982,Bangalore,Royal Challengers Bengaluru,223.0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,...,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
124149,1426312,Chennai,Kolkata Knight Riders,114.0,1426312,1,Sunrisers Hyderabad,Kolkata Knight Riders,17,5,...,SP Narine,PJ Cummins,0,0,0,NaN,1,JD Unadkat,lbw,NaN
124150,1426312,Chennai,Kolkata Knight Riders,114.0,1426312,1,Sunrisers Hyderabad,Kolkata Knight Riders,17,6,...,SP Narine,PJ Cummins,0,0,0,NaN,0,NaN,NaN,NaN
124151,1426312,Chennai,Kolkata Knight Riders,114.0,1426312,1,Sunrisers Hyderabad,Kolkata Knight Riders,18,1,...,AD Russell,B Kumar,0,0,0,NaN,0,NaN,NaN,NaN
124152,1426312,Chennai,Kolkata Knight Riders,114.0,1426312,1,Sunrisers Hyderabad,Kolkata Knight Riders,18,2,...,AD Russell,B Kumar,0,0,0,NaN,0,NaN,NaN,NaN
124153,1426312,Chennai,Kolkata Knight Riders,114.0,1426312,1,Sunrisers Hyderabad,Kolkata Knight Riders,18,3,...,AD Russell,B Kumar,0,0,0,NaN,1,PJ Cummins,caught,MA Starc

Here Total_runs_y colunm is in string format so We have to convert into int format.

In [152]:
match['total_runs_y'] = pd.to_numeric(match['total_runs'], errors='coerce')

Now we will calculate cumulative score per each

In [155]:
match['cumulative_runs'] = match.groupby('id')['total_runs'].cumsum()

In [157]:
match

,id,city,winner,target_runs,match_id,inning,batting_team,bowling_team,over,ball,...,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder,total_runs_y,cumulative_runs
0,335982,Bangalore,Royal Challengers Bengaluru,223.0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,...,0,1,1,legbyes,0,NaN,NaN,NaN,1,1
1,335982,Bangalore,Royal Challengers Bengaluru,223.0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,...,0,0,0,NaN,0,NaN,NaN,NaN,0,1
2,335982,Bangalore,Royal Challengers Bengaluru,223.0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,...,0,1,1,wides,0,NaN,NaN,NaN,1,2
3,335982,Bangalore,Royal Challengers Bengaluru,223.0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,...,0,0,0,NaN,0,NaN,NaN,NaN,0,2
4,335982,Bangalore,Royal Challengers Bengaluru,223.0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,...,0,0,0,NaN,0,NaN,NaN,NaN,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
124149,1426312,Chennai,Kolkata Knight Riders,114.0,1426312,1,Sunrisers Hyderabad,Kolkata Knight Riders,17,5,...,0,0,0,NaN,1,JD Unadkat,lbw,NaN,0,113
124150,1426312,Chennai,Kolkata Knight Riders,114.0,1426312,1,Sunrisers Hyderabad,Kolkata Knight Riders,17,6,...,0,0,0,NaN,0,NaN,NaN,NaN,0,113
124151,1426312,Chennai,Kolkata Knight Riders,114.0,1426312,1,Sunrisers Hyderabad,Kolkata Knight Riders,18,1,...,0,0,0,NaN,0,NaN,NaN,NaN,0,113
124152,1426312,Chennai,Kolkata Knight Riders,114.0,1426312,1,Sunrisers Hyderabad,Kolkata Knight Riders,18,2,...,0,0,0,NaN,0,NaN,NaN,NaN,0,113
124153,1426312,Chennai,Kolkata Knight Riders,114.0,1426312,1,Sunrisers Hyderabad,Kolkata Knight Riders,18,3,...,0,0,0,NaN,1,PJ Cummins,caught,MA Starc,0,113

In [159]:
match['runs_left']=match['target_runs']-match['cumulative_runs']

In [161]:
 match['balls_left']=120-(match['over']*6+match['ball'])

Here We Are calculating Wickets According to Score

In [164]:
match['is_wicket'] = pd.to_numeric(match['is_wicket'], errors='coerce').fillna(0).astype(int)

In [166]:
match['wickets'] = 10 - match.groupby('id')['is_wicket'].cumsum()

In [168]:
match

,id,city,winner,target_runs,match_id,inning,batting_team,bowling_team,over,ball,...,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder,total_runs_y,cumulative_runs,runs_left,balls_left,wickets
0,335982,Bangalore,Royal Challengers Bengaluru,223.0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,...,legbyes,0,NaN,NaN,NaN,1,1,222.0,119,10
1,335982,Bangalore,Royal Challengers Bengaluru,223.0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,...,NaN,0,NaN,NaN,NaN,0,1,222.0,118,10
2,335982,Bangalore,Royal Challengers Bengaluru,223.0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,...,wides,0,NaN,NaN,NaN,1,2,221.0,117,10
3,335982,Bangalore,Royal Challengers Bengaluru,223.0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,...,NaN,0,NaN,NaN,NaN,0,2,221.0,116,10
4,335982,Bangalore,Royal Challengers Bengaluru,223.0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,...,NaN,0,NaN,NaN,NaN,0,2,221.0,115,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
124149,1426312,Chennai,Kolkata Knight Riders,114.0,1426312,1,Sunrisers Hyderabad,Kolkata Knight Riders,17,5,...,NaN,1,JD Unadkat,lbw,NaN,0,113,1.0,13,1
124150,1426312,Chennai,Kolkata Knight Riders,114.0,1426312,1,Sunrisers Hyderabad,Kolkata Knight Riders,17,6,...,NaN,0,NaN,NaN,NaN,0,113,1.0,12,1
124151,1426312,Chennai,Kolkata Knight Riders,114.0,1426312,1,Sunrisers Hyderabad,Kolkata Knight Riders,18,1,...,NaN,0,NaN,NaN,NaN,0,113,1.0,11,1
124152,1426312,Chennai,Kolkata Knight Riders,114.0,1426312,1,Sunrisers Hyderabad,Kolkata Knight Riders,18,2,...,NaN,0,NaN,NaN,NaN,0,113,1.0,10,1
124153,1426312,Chennai,Kolkata Knight Riders,114.0,1426312,1,Sunrisers Hyderabad,Kolkata Knight Riders,18,3,...,NaN,1,PJ Cummins,caught,MA Starc,0,113,1.0,9,0

In [170]:
match['crr']=(match['cumulative_runs']*6)/(120-match['balls_left'])

In [172]:
match['rrr']=(match['runs_left']*6)/(match['balls_left'])

In [174]:
def result(row):
    return 1 if row['batting_team'] == row['winner'] else 0

In [176]:
match['result'] = match.apply(result,axis=1)

For Regression Model We Need batting_team,bowling_team,city,runs_left,balls_left,wickets,target,crr,rrr,result

In [178]:
final_df = match[['batting_team','bowling_team','city','runs_left','balls_left','wickets','target_runs','crr','rrr','result']]

In [181]:
final_df

,batting_team,bowling_team,city,runs_left,balls_left,wickets,target_runs,crr,rrr,result
0,Kolkata Knight Riders,Royal Challengers Bangalore,Bangalore,222.0,119,10,223.0,6.000000,11.193277,0
1,Kolkata Knight Riders,Royal Challengers Bangalore,Bangalore,222.0,118,10,223.0,3.000000,11.288136,0
2,Kolkata Knight Riders,Royal Challengers Bangalore,Bangalore,221.0,117,10,223.0,4.000000,11.333333,0
3,Kolkata Knight Riders,Royal Challengers Bangalore,Bangalore,221.0,116,10,223.0,3.000000,11.431034,0
4,Kolkata Knight Riders,Royal Challengers Bangalore,Bangalore,221.0,115,10,223.0,2.400000,11.530435,0
...,...,...,...,...,...,...,...,...,...,...
124149,Sunrisers Hyderabad,Kolkata Knight Riders,Chennai,1.0,13,1,114.0,6.336449,0.461538,0
124150,Sunrisers Hyderabad,Kolkata Knight Riders,Chennai,1.0,12,1,114.0,6.277778,0.500000,0
124151,Sunrisers Hyderabad,Kolkata Knight Riders,Chennai,1.0,11,1,114.0,6.220183,0.545455,0
124152,Sunrisers Hyderabad,Kolkata Knight Riders,Chennai,1.0,10,1,114.0,6.163636,0.600000,0
124153,Sunrisers Hyderabad,Kolkata Knight Riders,Chennai,1.0,9,0,114.0,6.108108,0.666667,0

In [183]:
final_df = final_df[final_df['balls_left'] != 0]

In [185]:
final_df = final_df.dropna()

Regression

In [188]:
X = final_df.iloc[:,:-1]
y = final_df.iloc[:,-1]
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=1)

In [190]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

trf = ColumnTransformer([
    ('trf', OneHotEncoder(sparse_output=False, drop='first'), ['batting_team', 'bowling_team', 'city'])
], remainder='passthrough',
    force_int_remainder_cols=False)

In [192]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.pipeline import Pipeline

pipe = Pipeline(steps=[
    ('step1',trf),
    ('step2',LogisticRegression(solver='liblinear'))
])

In [194]:
pipe.fit(X_train, y_train)

Pipeline(steps=[('step1',
                 ColumnTransformer(force_int_remainder_cols=False,
                                   remainder='passthrough',
                                   transformers=[('trf',
                                                  OneHotEncoder(drop='first',
                                                                sparse_output=False),
                                                  ['batting_team',
                                                   'bowling_team', 'city'])])),
                ('step2', LogisticRegression(solver='liblinear'))])

In [195]:
y_pred = pipe.predict(X_test)

In [196]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.7658124785738772

In [204]:
import pickle
pickle.dump(pipe,open('pipe.pkl','wb'))